### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by zautumnz** [demberto/FL-PluginDB-Organiser#1]
The path on Mac is the same as on Windows (`~/Documents/Image-line/FL Studio/Presets/Plugin database/Installed/`), but with the addition of an `AudioUnit` directory under both `Generators/` and `Effects/`. As far as I can tell it works on Mac otherwise.

**Comment by demberto** [comment]
I did say in the README that Mac users should raise an issue for Mac support, but I don't have a Mac myself.

Can you do a PR for this?

**Comment by zautumnz** [comment]
Sure, PR submitted!
